default: &default
  url: <%= ENV.fetch("REDIS_URL", "unix://#{Rails.root}/tmp/sockets/redis.sock?db=0") %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "unix://#{Rails.root}/tmp/sockets/redis.sock?db=1") %>

production:
  <<: *default
  # In production, you'll likely want to use TCP connection
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
